@tool
extends RefCounted
## Shared by the command-line runner and editor plugin. Never loads a battle or unit.

const CLASSES_DIRECTORY := "res://resources/classes"
const OUTPUT_PATH := "res://CLASS_ABILITIES.md"
const BASIC_ATTACKS := ["res://resources/abilities/strike.tres", "res://resources/abilities/arrow.tres"]


class BuildErrors extends Logger:
	var messages: Array[String] = []
	var mutex := Mutex.new()

	func _log_error(_function: String, file: String, line: int, code: String, rationale: String, _editor_notify: bool, error_type: int, _backtraces: Array) -> void:
		if error_type == ERROR_TYPE_WARNING:
			return
		mutex.lock()
		messages.append("%s:%d: %s" % [file, line, rationale if not rationale.is_empty() else code])
		mutex.unlock()


static func build(classes_directory: String = CLASSES_DIRECTORY) -> Dictionary:
	# Godot can return a partially loaded resource after a nested script/load error.
	# Capture those errors as well as validation failures before any output is written.
	var logger := BuildErrors.new()
	OS.add_logger(logger)
	var result := _build(classes_directory)
	OS.remove_logger(logger)
	if not logger.messages.is_empty():
		return _failure(logger.messages)
	if result.is_empty():
		return _failure(["Reference generation did not complete."])
	return result


static func _build(classes_directory: String) -> Dictionary:
	var errors: Array[String] = []
	var paths := _class_paths(classes_directory, errors)
	if paths.is_empty() and errors.is_empty():
		errors.append("No class resources found in %s." % classes_directory)
	var dependencies: Dictionary = {}
	for path in paths + BASIC_ATTACKS:
		_collect_dependencies(path, dependencies, errors)
	if not errors.is_empty():
		return _failure(errors)
	var classes: Array[Dictionary] = []
	var ids: Dictionary = {}
	for path in paths:
		# A deep uncached load reads saved nested abilities/statuses, not Inspector edits.
		var definition := ResourceLoader.load(path, "", ResourceLoader.CACHE_MODE_IGNORE_DEEP) as CharacterClassDefinition
		if definition == null:
			errors.append("Cannot load a CharacterClassDefinition from %s." % path)
			continue
		errors.append_array(definition.validate())
		if ids.has(definition.class_id):
			errors.append("Duplicate class ID %s in %s." % [definition.class_id, path])
		ids[definition.class_id] = true
		classes.append({"definition": definition, "path": path})
	classes.sort_custom(func(a: Dictionary, b: Dictionary) -> bool:
		var comparison := String(a.definition.display_name).nocasecmp_to(b.definition.display_name)
		return a.path < b.path if comparison == 0 else comparison < 0
	)
	if not errors.is_empty():
		return _failure(errors)
	var lines: Array[String] = [
		"# Class abilities",
		"",
		"> Automatically generated from saved Godot resources. Do not edit this file by hand.",
		"",
		"Unlock levels are levels invested in that class, not total character level. Abilities remain unlocked at higher levels. Multiclass characters combine their unlocks; shared abilities appear only once in their combat loadout.",
		"",
		"## At a glance",
		"",
		"| Class | New abilities by class level |",
		"| --- | --- |",
	]
	for entry in classes:
		var unlocks: Array[String] = []
		for unlock in entry.definition.get_sorted_unlocks():
			unlocks.append("**%d:** %s" % [unlock.required_level, _resource_link(unlock.ability)])
		lines.append("| %s | %s |" % [_link(entry.definition.display_name, entry.path), "; ".join(unlocks) if not unlocks.is_empty() else "No class unlocks"])
	lines.append_array([
		"",
		"## Basic attacks — all classes",
		"",
		"Every friendly class gets Strike when unarmed or using a melee weapon. A ranged weapon replaces it with Shoot. These basic attacks have no class-level requirement and occupy the first ability slot.",
		"",
		"Descriptions show base ranges and damage/healing formulas. Actual values depend on the character's effective stats, equipment, and statuses. Normal action and equipment requirements still apply.",
		"",
		"| Ability | Description |",
		"| --- | --- |",
	])
	for path in BASIC_ATTACKS:
		var ability := ResourceLoader.load(path, "", ResourceLoader.CACHE_MODE_IGNORE_DEEP) as AbilityDefinition
		if ability == null:
			errors.append("Cannot load basic attack %s." % path)
			continue
		lines.append("| %s | %s |" % [_link(ability.display_name, path), _describe(ability, errors)])
	for entry in classes:
		lines.append_array(["", "## %s" % _escape(entry.definition.display_name), "", "| Level | Ability | Description |", "| --- | --- | --- |"])
		var unlocks: Array[ClassAbilityUnlock] = entry.definition.get_sorted_unlocks()
		if unlocks.is_empty():
			lines.append("| — | — | No class unlocks; basic attacks are still available. |")
		elif unlocks[0].required_level > 1:
			lines.append("| 1 | Basic attack | Class abilities unlock at the levels below. |")
		for unlock in unlocks:
			lines.append("| %d | %s | %s |" % [unlock.required_level, _resource_link(unlock.ability), _describe(unlock.ability, errors)])
	lines.append_array([
		"",
		"## Updating this reference",
		"",
		"With the Class Ability Reference editor plugin enabled, saved changes refresh this file after a short delay. External edits refresh when Godot detects them; changes made while Godot is closed refresh when the project next opens. Unsaved Inspector edits are excluded.",
		"",
		"To refresh manually, use **Project → Tools → Regenerate Class Abilities**. From the project directory:",
		"",
		"```text",
		"godot --headless --path . --script res://addons/class_ability_reference/generate_reference.gd",
		"godot --headless --path . --script res://addons/class_ability_reference/generate_reference.gd -- --check",
		"```",
		"",
		"The second command checks for missing or outdated content without writing it. See [class authoring and progression](docs/character_classes.md) for editing instructions.",
		"",
	])
	return {"ok": true, "text": "\n".join(lines), "errors": errors} if errors.is_empty() else _failure(errors)


static func update(output_path: String = OUTPUT_PATH, classes_directory: String = CLASSES_DIRECTORY, check_only: bool = false) -> Dictionary:
	var result := build(classes_directory)
	result["changed"] = false
	if not result.ok:
		return result
	var exists := FileAccess.file_exists(output_path)
	if exists and FileAccess.get_file_as_string(output_path) == result.text:
		return result
	if check_only:
		return _failure(["%s is missing or out of date. Run the generator to refresh it." % output_path])
	# Write alongside the destination, then replace it only after a complete write.
	var temporary_path := "%s.tmp-%d-%d" % [output_path, OS.get_process_id(), Time.get_ticks_usec()]
	var file := FileAccess.open(temporary_path, FileAccess.WRITE)
	if file == null:
		return _failure(["Cannot write %s: %s" % [temporary_path, error_string(FileAccess.get_open_error())]])
	file.store_string(result.text)
	file.flush()
	var write_error := file.get_error()
	file.close()
	if write_error != OK:
		DirAccess.remove_absolute(temporary_path)
		return _failure(["Cannot complete %s: %s" % [temporary_path, error_string(write_error)]])
	var rename_error := DirAccess.rename_absolute(temporary_path, output_path)
	if rename_error != OK:
		DirAccess.remove_absolute(temporary_path)
		return _failure(["Cannot replace %s: %s" % [output_path, error_string(rename_error)]])
	result.changed = true
	return result


## Only source content participates: generated Markdown, editor logs, and caches do not.
static func input_fingerprint(classes_directory: String = CLASSES_DIRECTORY) -> String:
	var errors: Array[String] = []
	var paths := _class_paths(classes_directory, errors)
	var dependencies: Dictionary = {}
	for path in paths + BASIC_ATTACKS:
		_collect_dependencies(path, dependencies, errors)
	# Include description helpers whose calls aren't serialized resource dependencies.
	_collect_scripts("res://scripts", dependencies)
	_collect_scripts("res://addons/class_ability_reference", dependencies)
	var sorted_paths := dependencies.keys()
	sorted_paths.sort()
	var parts: Array[String] = [classes_directory]
	for path in sorted_paths:
		parts.append("%s:%s" % [path, FileAccess.get_sha256(path) if FileAccess.file_exists(path) else "missing"])
	parts.append_array(errors)
	return "\n".join(parts).sha256_text()


static func _class_paths(directory: String, errors: Array[String]) -> Array[String]:
	var paths: Array[String] = []
	var dir := DirAccess.open(directory)
	if dir == null:
		errors.append("Cannot read classes directory %s." % directory)
		return paths
	for child in dir.get_directories():
		if not child.begins_with("."):
			paths.append_array(_class_paths(directory.path_join(child), errors))
	for file_name in dir.get_files():
		if file_name.get_extension().to_lower() in ["tres", "res"]:
			paths.append(directory.path_join(file_name))
	paths.sort()
	return paths


static func _collect_dependencies(path: String, found: Dictionary, errors: Array[String]) -> void:
	if found.has(path):
		return
	found[path] = true
	if not FileAccess.file_exists(path):
		errors.append("Missing resource dependency: %s" % path)
		return
	for dependency in ResourceLoader.get_dependencies(path):
		var dependency_path := dependency.get_slice("::", dependency.get_slice_count("::") - 1)
		if dependency_path.begins_with("uid://"):
			var uid := ResourceUID.text_to_id(dependency_path)
			if ResourceUID.has_id(uid):
				dependency_path = ResourceUID.get_id_path(uid)
		_collect_dependencies(dependency_path, found, errors)


static func _collect_scripts(directory: String, found: Dictionary) -> void:
	var dir := DirAccess.open(directory)
	if dir == null:
		return
	for child in dir.get_directories():
		if not child.begins_with("."):
			_collect_scripts(directory.path_join(child), found)
	for file_name in dir.get_files():
		if file_name.get_extension() == "gd":
			found[directory.path_join(file_name)] = true


static func _describe(ability: AbilityDefinition, errors: Array[String]) -> String:
	var configuration_error := ability.get_targeting_configuration_error()
	if not configuration_error.is_empty():
		errors.append("%s: %s" % [ability.display_name, configuration_error])
	var description := ability.get_description()
	if description.strip_edges().is_empty():
		errors.append("Empty description for %s." % ability.display_name)
	var recipients: Array[String] = []
	for entry in [[AbilityDefinition.TargetFlags.FRIEND, "allies"], [AbilityDefinition.TargetFlags.ENEMY, "enemies"], [AbilityDefinition.TargetFlags.SELF, "self"]]:
		if ability.has_target_flag(entry[0]):
			recipients.append(entry[1])
	description += " | Affects: %s" % (", ".join(recipients) if not recipients.is_empty() else "no units")
	if ability.has_target_flag(AbilityDefinition.TargetFlags.CELL) and not ability.caster_centered:
		description += " | Can aim at a cell"
	if not ability.caster_centered:
		if ability.shape == AbilityDefinition.Shape.LINE_FROM_CASTER:
			description += " | Line from caster toward target"
		elif ability.get_effective_area_span() > 1:
			var shape_name: String = AbilityDefinition.Shape.keys()[ability.shape].to_lower().replace("_", " ")
			description += " | Area: %s, %d-cell span" % [shape_name, ability.get_effective_area_span()]
	match ability.get_required_weapon_type():
		ItemDefinition.WeaponType.MELEE:
			description += " | Melee weapon required" if not ability.allow_unarmed_for_friendlies else " | Melee weapon or unarmed friendly"
		ItemDefinition.WeaponType.RANGED:
			description += " | Ranged weapon required"
		_:
			description += " | No weapon required"
	if ability.accepts_weapon_range_bonus:
		description += " | Compatible weapon range bonuses extend normal attacks"
	return _escape(description.replace(" | ", ". ")) + "."


static func _resource_link(resource: Resource) -> String:
	return _link(resource.display_name, resource.resource_path)


static func _link(label: String, path: String) -> String:
	if path.is_empty():
		return _escape(label)
	var target := path.get_slice("::", 0).trim_prefix("res://").uri_encode().replace("%2F", "/")
	return "[%s](%s)" % [_escape(label), target]


static func _escape(value: String) -> String:
	var escaped := value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
	for character in ["\\", "|", "[", "]", "*", "_", "`", "#"]:
		escaped = escaped.replace(character, "\\" + character)
	return escaped.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "<br>")


static func _failure(errors: Array[String]) -> Dictionary:
	return {"ok": false, "text": "", "changed": false, "errors": errors}
