class_name GeneralInventory
extends Node

signal items_changed

@export_category("Starting Inventory")
## Unused items available when the battle begins. Each entry represents one copy.
## Repeat an ItemDefinition in this list to start with multiple copies.
@export var starting_items: Array[ItemDefinition] = []

var _items: Array[ItemDefinition] = []
var revision: int = 0
var _transferring: bool = false


func _ready() -> void:
	initialize_starting_items(starting_items)


## Replaces the runtime contents with a copy of the scene's configured unused items.
## Empty Inspector array entries are ignored so partially authored lists remain safe.
func initialize_starting_items(items: Array[ItemDefinition]) -> void:
	_items.clear()
	for item in items:
		if item != null:
			_items.append(item)
	_changed()


func get_items() -> Array[ItemDefinition]:
	var result: Array[ItemDefinition] = []
	for item in _items:
		if item != null:
			result.append(item)
	return result


## Unlike get_items(), this snapshot includes vacant grid cells.
func get_slots() -> Array[ItemDefinition]:
	return _items.duplicate()


func get_item_at(index: int) -> ItemDefinition:
	return _items[index] if index >= 0 and index < _items.size() else null


func first_empty_slot() -> int:
	var index := _items.find(null)
	return index if index >= 0 else _items.size()


func add_item(item: ItemDefinition) -> void:
	if item == null or _transferring:
		return
	_put(first_empty_slot(), item)
	_changed()


func take_item(item: ItemDefinition) -> bool:
	var index := _items.find(item)
	if item == null or index < 0 or _transferring:
		return false
	_items[index] = null
	_changed()
	return true


func can_move_or_swap(source: int, destination: int) -> bool:
	return not _transferring and destination >= 0 and get_item_at(source) != null


func move_or_swap(source: int, destination: int) -> bool:
	if not can_move_or_swap(source, destination):
		return false
	if source == destination:
		return true
	var item := _items[source]
	_items[source] = get_item_at(destination)
	_put(destination, item)
	_changed()
	return true


func can_equip_from_slot(index: int, character: TacticalCharacter, slot: int) -> bool:
	var item := get_item_at(index)
	return not _transferring and _valid_character(character) and item != null and item.slot == slot


## Inventory is updated before the character emits equipment/stat signals, so
## observers see the complete swap. Only one inventory notification is emitted.
func equip_from_slot(index: int, character: TacticalCharacter, slot: int) -> bool:
	if not can_equip_from_slot(index, character, slot):
		return false
	_transferring = true
	var item := _items[index]
	var displaced := character.get_displaced_items(item)
	_items[index] = null if displaced.is_empty() else displaced[0]
	for extra in displaced.slice(1):
		_put(first_empty_slot(), extra)
	_trim_empty_tail()
	revision += 1
	character.equip_item(item)
	_transferring = false
	_changed(false)
	return true


func can_unequip_to_slot(character: TacticalCharacter, slot: int, destination: int) -> bool:
	if _transferring or not _valid_character(character) or destination < 0:
		return false
	if not ItemDefinition.EquipmentSlot.values().has(slot) or character.get_equipped_item(slot) == null:
		return false
	var replacement := get_item_at(destination)
	return replacement == null or replacement.slot == slot


## An occupied destination is legal only if its item can be equipped in return.
func unequip_to_slot(character: TacticalCharacter, slot: int, destination: int) -> bool:
	if not can_unequip_to_slot(character, slot, destination):
		return false
	_transferring = true
	var replacement := get_item_at(destination)
	_put(destination, character.get_equipped_item(slot))
	if replacement != null:
		# The first displaced item already occupies the requested destination.
		for extra in character.get_displaced_items(replacement).slice(1):
			_put(first_empty_slot(), extra)
	revision += 1
	if replacement == null:
		character.unequip_item(slot)
	else:
		character.equip_item(replacement)
	_transferring = false
	_changed(false)
	return true


func _valid_character(character: TacticalCharacter) -> bool:
	return is_instance_valid(character) and not character.is_queued_for_deletion() and character.current_health > 0


func _put(index: int, item: ItemDefinition) -> void:
	if index >= _items.size():
		_items.resize(index + 1)
	_items[index] = item


func _trim_empty_tail() -> void:
	# Trailing presentation cells are regenerated by the UI; interior gaps persist.
	while not _items.is_empty() and _items.back() == null:
		_items.pop_back()


func _changed(increment_revision: bool = true) -> void:
	_trim_empty_tail()
	if increment_revision:
		revision += 1
	items_changed.emit()


func capture_state() -> Array[String]:
	var paths: Array[String] = []
	for item in _items:
		paths.append(item.resource_path if item != null else "")
	return paths


func restore_state(paths: Array) -> void:
	paths = ItemDefinition.normalize_saved_paths(paths)
	_items.clear()
	for value in paths:
		var path := str(value)
		var item: ItemDefinition = null
		if not path.is_empty() and ResourceLoader.exists(path):
			item = load(path) as ItemDefinition
		_items.append(item)
	_changed()
